locators = {
    'button': '[data-show="gids"]',
    'genres_picker': '#genrebox',
    'apply_filter': '#applymsg',
    'painting': '.post > a > [itemprop="name"]',
    'genre': 'div.txtline.lft > a',
    'post': '.post',
    'heart_btn': '.heart',
    'paiting_name': 'a > [itemprop="name"]',
    'likes_list': '.topheader > .fvtico',
    'painting_name_in_list': '.post > a > div',
    'search': '[name="qs"]',
    'enter_search': '[type="submit"]',
    'cart_btn': '.oclick',
    'paiting_price': '.price',
    'go_cart_in_modal': '.ok-button',
    'cart_item': '.c_row',
    'cart_item_name': '.c_name > a',
    'cart_item_price': '.shop > .price',
}
